version: '2'
services:
  bangrz:
    build:
      context: ./config/php_nginx
      dockerfile: Dockerfile
    image: dockerico/app
    volumes:
     - ./app:/var/www/html
    ports:
     - "${BANGRZ_PORT}:80"
    networks:
     - appnet
  node:
    build:
      context: ./config/node
      dockerfile: Dockerfile
    image: dockerico/node
    volumes:
     - ./app:/var/www/html
    networks:
     - appnet
  mysql:
    image: mysql:5.7
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - appnet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
